### ISSUE TITLE
Longer time to train a BERT-fused model

### ISSUE THREAD

**Issue by gvskalyan** [bert-nmt/bert-nmt#18]
Hi,
I trained a NMT model for low resource language in fairseq, it takes 30 seconds for an epoch on 8*2080ti GPUs, on a dataset containing 0.3M sentences and the architecture is transformer-base.

Using the same data and `transformers2` as architecture, am getting around 20 minutes per epoch.
Used the train command present [here](https://github.com/bert-nmt/bert-nmt#train-a-bert-fused-nmt-model).

Note :  Enabled args `update-freq 16 , --fp16 and ddp_backend no_c10d` . 
Can you please infer from these why the training time is too high. Thanks.

**Comment by teslacool** [comment]
Did you keep the arguments in Fairseq (not those we added in bertnmt) unchanged?

**Comment by gvskalyan** [comment]
Yes I kept it unchanged.
This is my exact command,
```python train.py $DATAPATH -a transformers2 --optimizer adam --lr 0.0005 -s $src -t $tgt --label-smoothing 0.1 --dropout 0.2 --max-tokens 4000 --min-lr '1e-09' --lr-scheduler inverse_sqrt --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --max-update 150000 --warmup-updates 4000 --warmup-init-lr '1e-07' --adam-betas '(0.9,0.98)' --save-dir $SAVEDIR --share-all-embeddings $warmup --encoder-bert-dropout --encoder-bert-dropout-ratio 0.5 --update-freq 16 --fp16 --ddp_backend no_c10d | tee -a $SAVEDIR/training.log```

Also can you please provide command/ procedure to use pre-trained XLM from this [repo](https://github.com/facebookresearch/xlm).

**Comment by teslacool** [comment]
This command is almost exactly the same as mine, except for the fp16 parameter.

But our experiments here have never seen such a huge gap. Can you check other arguments, such as removing fp16, or other parameters, such as the number of gpus.

Or you can use the iwslt14 data set to compare the training time of bertnmt and fairseq.

Yes, our unsupervised experiment is based on the xlm code and is not included in this repo. Due to limited time, it has not been organized and open source. I will take the time to sort out recently and make it public. Thank you.

**Comment by gvskalyan** [comment]
Removing fp16 made the epoch faster. Comparing with non-fp16 of fairseq, training time is okay since BERT is fused.

**Comment by teslacool** [comment]
Since i have not set this flag, maybe I have not implement this corresponding function for bert module.
